Run tempest tests
The utility_all group was not added to nova and the tempest tests are
not being run against the tempest host.

Additionally, scheduling fails if the ansible_host for localhost is
"localhost", it needs to be set to an IP to prevent failures such as:

ValueError: failed to detect a valid IP address from 'localhost'

The defaulted "neutron_provider_networks" in the common test repository
takes precedence over the host_vars in the repository, we need to change
this by setting it in the nova-overrides.

This PR fixes that.

Change-Id: If7b731814a16593434952300679deb286093d899
(cherry picked from commit a2ffeab2cafc055ac67cb95bc89ae5903bffb681)